Useful Code:
  Application.yml
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgres://jswtyqturdjopc:1fccba4e64eac1036cc1c985063839d7690b03fb744269a71871bc619eafbef5@ec2-54-220-35-19.eu-west-1.compute.amazonaws.com:5432/d4ua52gm9p2ukc
    username: jswtyqturdjopc
    password: 1fccba4e64eac1036cc1c985063839d7690b03fb744269a71871bc619eafbef5